# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

# Organise imports
-   repo: https://github.com/PyCQA/isort
    rev: '5.11.4'
    hooks:
    -   id: isort

# Update all old python syntax
-   repo: https://github.com/asottile/pyupgrade
    rev: 'v3.3.1'
    hooks:
    -   id: pyupgrade

# Format with Black
-   repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
    -   id: black

# Lint with flake8
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
        args: ['--per-file-ignores=**/__init__.py:F401']

# It uses the locally installed (need mypy installed locally) since the mirror
# by default uses opionated args
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]