# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

# Organise imports
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    -   id: isort

# Update all old python syntax
-   repo: https://github.com/asottile/pyupgrade
    rev: 'v3.1.0'
    hooks:
    -   id: pyupgrade

# Format with Black
-   repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
    -   id: black

# Lint with flake8
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: ['--per-file-ignores=**/__init__.py:F401']

# Static type check with mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
    -   id: mypy