# For Black pre-commit hook
[tool.black]
line-length = 79

# So isort is compatible with black
[tool.isort]
profile = "black"

# mypy
[tool.mypy]

[[tool.mypy.overrides]]
module = [
    'scipy.*',
    'networkx',
    'dd'
]
ignore_missing_imports = true

# Coverage
[tool.coverage.run]
source = ["repyability"]

# Flake8
[tool.flake8]
ignore = ['E203', 'W503']
per-file-ignores = [
    '*/__init__.py:F401',
]