# For Black pre-commit hook
[tool.black]
line-length = 79

# So isort is compatible with black
[tool.isort]
profile = "black"

# For mypy to better analyse numpy type hints
[mypy]
plugins = "numpy.typing.mypy_plugin"

# Coverage
[tool.coverage.run]
source = ["repyability"]
