# Per pytest docs recommendation
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

# For Black pre-commit hook
[tool.black]
line-length = 79

# So isort is compatible with black
[tool.isort]
profile = "black"

# For mypy to better analyse numpy type hints
[mypy]
plugins = "numpy.typing.mypy_plugin"

# Ignore untyped libraries scipy, networkx, and surpyval
[tool.mypy]
ignore_missing_imports = true

# Coverage
[tool.coverage.run]
source = ["repyability"]
